# Generated by Django 3.2.13 on 2022-05-06 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djeym', '0002_auto_20220506_1553'),
        ('meetups', '0003_alter_tag_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meetups.meetup')),
                ('placemark', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='djeym.placemark')),
            ],
        ),
    ]
