# Generated by Django 3.2.13 on 2022-05-10 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetups', '0007_auto_20220503_1300'),
        ('djeym', '0002_auto_20220510_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marker', to='meetups.meetup')),
                ('placemark', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marker', to='djeym.placemark')),
            ],
        ),
    ]
