# Generated by Django 3.2.13 on 2022-05-06 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djeym', '0002_auto_20220506_1553'),
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='placemark',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='djeym.placemark'),
        ),
    ]
