# Generated by Django 3.2.13 on 2022-05-03 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_auto_20220430_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='slug',
            field=models.SlugField(default='qwer', verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='meetups.tag', verbose_name='Родитель'),
        ),
    ]
