# Generated by Django 3.2.13 on 2022-05-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_alter_meetup_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='meetups', to='meetups.Tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='website',
            field=models.URLField(blank=True, verbose_name='Сайт'),
        ),
    ]
