# Generated by Django 3.2.13 on 2022-05-14 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetups', '0007_auto_20220503_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='lecturers',
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('time', models.TimeField(verbose_name='Время')),
                ('lectors', models.ManyToManyField(related_name='lectures', to=settings.AUTH_USER_MODEL, verbose_name='Лекторы/Лектор')),
                ('meetup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='meetups.meetup', verbose_name='Митап')),
            ],
            options={
                'verbose_name': 'Лекция',
                'verbose_name_plural': 'Лекции',
            },
        ),
    ]
